### PR TITLE
Fix memory leaks in native code

### LINKED ISSUE #405: out-of-memory in ExampleFuzzer with keep_going
Please check the ExampleFuzzer with option `--keep_going` more than 1.

```
java_fuzz_target_test(
    name = "ExampleFuzzer",
    ...
    fuzzer_args = [
        "--keep_going=10",
    ],
)

```

With `export JAVA_OPTS='-verbose:gc'` I can see that heap is full after a few minutes.
Checked on 3b473ad

```
$ BAZEL_DO_NOT_DETECT_CPP_TOOLCHAIN=1 ./bazelisk run --config=toolchain --extra_toolchains=@llvm_toolchain//:cc-toolchain-x86_64-linux //examples:ExampleFuzzer
...
[Full GC (Ergonomics)  1519600K->1519599K(1677312K), 1.4917747 secs]
[Full GC (Ergonomics)  1519600K->1519527K(1677312K), 3.3910757 secs]
[Full GC (Ergonomics)  1519529K->1519528K(1677312K), 1.4910728 secs]
[Full GC (Ergonomics)  1519529K->1519396K(1677312K), 3.2149110 secs]
...
```

Is it an issue?

### PR DESCRIPTION
**Pull request by fmeum**
Fixes #405.

### CODE REVIEW

**Comment by fmeum** [comment]
@bertschneider The failing test is broken by https://github.com/CodeIntelligenceTesting/jazzer/pull/406/commits/553b1a231d610101b35b96ef72b04bc91ab1d551. Do you have an idea why?

**Comment by bertschneider** [comment]
The class `NoClassDefFoundError` is also present on the `main` branch, the test is not failing, though. I'm looking into it.

File: bazel/tools/java/com/code_intelligence/jazzer/tools/FuzzTargetTestWrapper.java [hunk 1]
```diff
@@ -92,30 +97,40 @@ public static void main(String[] args) {
...
       // 76).
       if (exitCode != 76 && exitCode != 77) {
-        System.exit(3);
+        System.err.printf("Did expect a crash, but Jazzer exited with exit code %d%n", exitCode);
+        System.exit(1);
       }
       String[] outputFiles = new File(outputDir).list();
       if (outputFiles == null) {
-        System.exit(4);
+        System.err.printf("Jazzer did not a crashing input into %s%n", outputDir);
```
Comment (bertschneider) [inline bazel/tools/java/com/code_intelligence/jazzer/tools/FuzzTargetTestWrapper.java:116]: Missing verb.

File: bazel/tools/java/com/code_intelligence/jazzer/tools/FuzzTargetTestWrapper.java [hunk 2]
```diff
@@ -46,16 +46,25 @@ public static void main(String[] args) {
...
+      expectCrash = Boolean.parseBoolean(args[5]);
       expectedFindings =
-          Arrays.stream(args[5].split(",")).filter(s -> !s.isEmpty()).collect(Collectors.toSet());
+          Arrays.stream(args[6].split(",")).filter(s -> !s.isEmpty()).collect(Collectors.toSet());
+      // Map all files/dirs to real location
+      arguments =
+          Arrays.stream(args)
+              .skip(7)
+              .map(arg -> arg.startsWith("-") ? arg : lookUpRunfileWithFallback(runfiles, arg))
+              .collect(Collectors.toList());
```
Comment (bertschneider) [inline bazel/tools/java/com/code_intelligence/jazzer/tools/FuzzTargetTestWrapper.java:67]: `arguments` could be of type `Stream<String>` to prevent the conversion into `List` and later back to `Stream`.

**Review by bertschneider — APPROVED** [review]
